# Generated by Django 5.0.6 on 2024-06-16 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0002_alter_profile_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.TextField(blank=True, null=True)),
                ('work_experience', models.CharField(max_length=255)),
                ('education', models.CharField(max_length=255)),
                ('certification', models.CharField(max_length=255)),
            ],
        ),
    ]
